# Config file for automatic testing at travis-ci.org
language: python

matrix:
    include:
      # Python version is just for the look on travis.
        - python: 3.4
          env: TOX_ENV=py34-unit-tests

        - python: 3.4
          env: TOX_ENV=py34-acceptance-tests

        - python: 3.5
          env: TOX_ENV=py35-unit-tests

        - python: 3.5
          env: TOX_ENV=py35-acceptance-tests

        - env: TOX_ENV=linters

install:
  - pip install tox codecov

script:
  - tox -e $TOX_ENV

after_success:
  - codecov
